#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Load package manager specific configuration
[ -f ~/.zpackagemanagers ] && source ~/.zpackagemanagers

# Prefer brew installed coreutils 
export PATH="$(brew --prefix coreutils)/libexec/gnubin:/usr/local/bin:$PATH"
export MAN_PATH="$(brew --prefix coreutils)/opt/coreutils/libexec/gnuman:$MAN_PATH"

# aliases for zsh configuration
alias _zs="exec zsh"
alias ls="ls --color=auto"
